### ISSUE TITLE
EventHubs.pm refers to entity_path in the authorizer, but SAS.pm has no such field

### ISSUE THREAD

**Issue by aufflick** [ytnobody/p5-Net-Azure-EventHubs#1]
Both in the CPAN versions and the head of your GitHub repos, there seems to be a version mismatch on how you create the URL.

```
sub message {
    my ($self, $payload) = @_;
    my $path = sprintf "/%s/messages", $self->authorizer->{entity_path};
    my $req = $self->_req($path => $payload);
    $req;
}

```

**Comment by aufflick** [comment]
Oh wait, my bad - I believed grep, but actually you're just de-camelizing the keys from the connection string (which I think I have wrong). Sorry!

**Comment by ytnobody** [comment]
@aufflick

Thank you for contact, and enjoy hacking ;)

If you find another issue, please report it.
Best regards.
