### ISSUE TITLE
t/13_req.t may fail

### ISSUE THREAD

**Issue by eserte** [ytnobody/p5-Net-Azure-EventHubs#3]
Sometimes t/13_req.t fails like this:
```
    #   Failed test 'Authorization header is generated completely'
    #   at t/13_req.t line 51.
    #          got: 'SharedAccessSignature sr=https%3a%2f%2fmysvc.servicebus.windows.net%2ffoo&sig=kZvfK4isHHk7xckoNMO2kA5L%2FR9WO1eQ4ohqgmCBkH0%3D&se=1544621365&skn=mykey'
    #     expected: 'SharedAccessSignature sr=https%3a%2f%2fmysvc.servicebus.windows.net%2ffoo&sig=Kw68RnowI%2FeWYs5GNcNwRLjXsVF3muzK%2BxR%2FfFNdCEg%3D&se=1544621366&skn=mykey'
    # Looks like you failed 1 test of 8.

#   Failed test 'with path, payload'
#   at t/13_req.t line 53.
# Looks like you failed 1 test of 6.
t/13_req.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
```

More similar reports on CPAN Testers:
* http://www.cpantesters.org/cpan/report/96632975
* http://www.cpantesters.org/cpan/report/96547667
* http://www.cpantesters.org/cpan/report/96547216

**Comment by ytnobody** [comment]
Maybe, here is causing.

https://github.com/ytnobody/p5-Net-Azure-Authorization-SAS/blob/master/lib/Net/Azure/Authorization/SAS.pm#L52

Net::Azure::EventHubs uses Net::Azure::Authorization::SAS for making an authorization header. 
In token() of N::A::A::SAS, signature is generated and affected by time().

I think Test::Time is good solution for resolve this issue.

- [x] use Test::Time for testing

**Comment by ytnobody** [comment]
It seems that made stabilize in b8724b2

**Comment by ytnobody** [comment]
Note: This issue will be closed at 2018-12-21T02:00:00Z

**Comment by eserte** [comment]
On my smoker systems it looks fine: no test failures with the recent release.

**Comment by ytnobody** [comment]
@eserte 
Thank you for reporting.

I saw another error that raised at a MSWin32 smoker system. 
But it's not related to this issue. 
http://www.cpantesters.org/cpan/report/a3f8c167-6bf9-1014-9920-10f0225761ff
